### PR TITLE
Yew v0.20

### PR DESCRIPTION
**Pull request by SionoiS**
I updated to yew-agent v0.2, yew 0.20 and yew-router 0.17

I fixed modals but unfortunately, I don't use them in my project and can't do extensive testing.

### CODE REVIEW

**Review by thedodd — COMMENTED** [review]
Nice! Thanks for doing this! I'm thinking it might be good to call this `0.4.0-alpha.0` in the Cargo.toml and changelog. I have not been able to test this code, so I think that might be a good idea. 

Thoughts?

**Comment by SionoiS** [comment]
I made the changes.

Maybe someone from the community will test it at some point? Since it's alpha maybe call it good enough? :shrug:

**Comment by matthiasbeyer** [comment]
Hi! Any plans to land this? yew 0.20 is out for a few days already... :laughing:

**Comment by rednaks** [comment]
anynews on this ? looks like builds are not succeeding ?

**Comment by thedodd** [comment]
@SionoiS I was having trouble resolving merge compatibility issues with this branch originally. Do you mind stashing your changes to the two pertinent components, recreating this branch fresh off of upstream master, and then applying your stashed changes as a new commit? 

v0.4.0-beta.0 should be released quite soon, but I want to incorporate your component changes here as well. Thanks for your patience.

**Comment by SionoiS** [comment]
The git history is a mess sorry I'll fix that later.

edit: or squash and merge call it a day.

**Pull request closed without merging**
